"""Localization helpers for Telegram Linux Admin."""

from __future__ import annotations

from typing import Dict

DEFAULT_LANGUAGE = "en"

LANGUAGE_LABELS = {
    "en": "🇺🇸 English",
    "ar": "🇸🇦 العربية",
    "fa": "🇮🇷 فارسی",
    "fr": "🇫🇷 Français",
    "de": "🇩🇪 Deutsch",
    "es": "🇪🇸 Español",
    "pt": "🇵🇹 Português",
    "it": "🇮🇹 Italiano",
    "ru": "🇷🇺 Русский",
    "tr": "🇹🇷 Türkçe",
    "zh": "🇨🇳 简体中文",
    "ja": "🇯🇵 日本語",
    "ko": "🇰🇷 한국어",
    "hi": "🇮🇳 हिन्दी",
    "ur": "🇵🇰 اردو",
}

TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "en": {
        "main_menu_welcome": "🐧 **Welcome to your Linux Admin Bot!**\n\nWhat would you like to do?",
        "button_connect_server": "🔌 Connect to a Server",
        "button_add_server": "➕ Add Server",
        "button_remove_server": "➖ Remove Server",
        "button_language_settings": "🌐 Language",
        "button_back_main_menu": "🔙 Back to Main Menu",
        "add_server_prompt": "🖥️ **Add a New Server**\n\nLet's add a new server. What short alias should we use? (e.g., `webserver`)",
        "prompt_hostname": "Great. Now, what is the hostname or IP address?",
        "prompt_username": "And the SSH username?",
        "prompt_auth_method": "How would you like to authenticate?",
        "prompt_password": "Please enter the SSH password.",
        "prompt_key_path": "Please enter the full path to your SSH private key on the server running this bot.",
        "button_auth_key": "🔑 Key",
        "button_auth_password": "🔒 Password",
        "server_added": "✅ **Server `{alias}` added successfully!**",
        "connect_menu_prompt": "**Select a server to connect to:**",
        "no_servers_configured": "No servers configured. Add one first!",
        "server_limit_reached": "⚠️ **Server limit reached.** Your plan allows {limit} servers. Remove one or upgrade to add more.",
        "no_servers_to_remove": "🤷 **No servers to remove.**",
        "server_not_found": "❌ **Server `{alias}` was not found.**",
        "server_removed": "🗑️ **Server `{alias}` removed successfully.**",
        "connecting_to_server": "🔌 **Connecting to {alias}...**",
        "connected_to_server": "✅ **Connected to {alias}!**\n\nWhat would you like to do?",
        "error_auth_failed": "❌ **Authentication Failed:**\nPermission denied. Check your username, password, or SSH key.",
        "error_connection_refused": "❌ **Connection Refused:**\nCould not reach `{alias}`. The server may be down or port 22 may be closed.",
        "error_host_not_found": "❌ **Host Not Found:**\nUnable to resolve `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Connection Error (202012):**\nEncountered SSH error 202012. Please verify the remote host and any jump hosts.",
        "error_generic_connection": "❌ **Connection Failed:**\nAn unexpected error occurred while connecting to `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Language Preferences**",
        "language_menu_description": "Select your preferred language. Current selection: {language_name}.",
        "language_updated": "✅ Language updated to {language_name}.",
        "language_saved_toast": "Language saved!",
        "language_unsupported": "Unsupported language.",
    },
    "ar": {
        "main_menu_welcome": "🐧 **مرحبًا بك في روبوت إدارة لينكس!**\n\nماذا تريد أن تفعل؟",
        "button_connect_server": "🔌 الاتصال بخادم",
        "button_add_server": "➕ إضافة خادم",
        "button_remove_server": "➖ إزالة خادم",
        "button_language_settings": "🌐 اللغة",
        "button_back_main_menu": "🔙 العودة إلى القائمة الرئيسية",
        "add_server_prompt": "🖥️ **إضافة خادم جديد**\n\nلنقم بإضافة خادم. ما الاسم المختصر الذي نستخدمه؟ (مثال: `webserver`)",
        "prompt_hostname": "رائع. ما اسم المضيف أو عنوان الـ IP؟",
        "prompt_username": "وما هو اسم مستخدم SSH؟",
        "prompt_auth_method": "كيف تريد المصادقة؟",
        "prompt_password": "يرجى إدخال كلمة مرور SSH.",
        "prompt_key_path": "أدخل المسار الكامل إلى مفتاحك الخاص SSH على الخادم الذي يعمل عليه البوت.",
        "button_auth_key": "🔑 مفتاح",
        "button_auth_password": "🔒 كلمة مرور",
        "server_added": "✅ **تمت إضافة الخادم `{alias}` بنجاح!**",
        "connect_menu_prompt": "**اختر خادمًا للاتصال به:**",
        "no_servers_configured": "لا توجد خوادم مضافة. يرجى إضافة خادم أولًا!",
        "server_limit_reached": "⚠️ **تم بلوغ حد الخوادم.** خطتك تسمح بـ {limit} خوادم. احذف خادمًا أو قم بالترقية لإضافة المزيد.",
        "no_servers_to_remove": "🤷 **لا توجد خوادم للحذف.**",
        "server_not_found": "❌ **الخادم `{alias}` غير موجود.**",
        "server_removed": "🗑️ **تمت إزالة الخادم `{alias}` بنجاح.**",
        "connecting_to_server": "🔌 **جارٍ الاتصال بـ {alias}...**",
        "connected_to_server": "✅ **تم الاتصال بـ {alias}!**\n\nما الذي ترغب بفعله؟",
        "error_auth_failed": "❌ **فشل المصادقة:**\nتم رفض الوصول. تحقق من اسم المستخدم أو كلمة المرور أو مفتاح SSH.",
        "error_connection_refused": "❌ **تم رفض الاتصال:**\nتعذر الوصول إلى `{alias}`. قد يكون الخادم متوقفًا أو أن المنفذ 22 مغلق.",
        "error_host_not_found": "❌ **تعذر العثور على المضيف:**\nلم يتمكن البوت من الوصول إلى `{alias}`. يرجى التحقق من العنوان.\n\n`{error}`",
        "error_code_202012": "❌ **خطأ في الاتصال (202012):**\nحدث الخطأ 202012 أثناء الاتصال. تحقق من إعدادات الشبكة أو خادم SSH.",
        "error_generic_connection": "❌ **فشل الاتصال:**\nحدث خطأ غير متوقع أثناء الاتصال بـ `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **إعدادات اللغة**",
        "language_menu_description": "اختر لغتك المفضلة. اللغة الحالية: {language_name}.",
        "language_updated": "✅ تم تحديث اللغة إلى {language_name}.",
        "language_saved_toast": "تم حفظ اللغة!",
        "language_unsupported": "هذه اللغة غير مدعومة.",
    },
    "fa": {
        "main_menu_welcome": "🐧 **به ربات مدیریت لینوکس خوش آمدید!**\n\nمایلید چه کاری انجام دهید؟",
        "button_connect_server": "🔌 اتصال به سرور",
        "button_add_server": "➕ افزودن سرور",
        "button_remove_server": "➖ حذف سرور",
        "button_language_settings": "🌐 زبان",
        "button_back_main_menu": "🔙 بازگشت به منوی اصلی",
        "add_server_prompt": "🖥️ **افزودن سرور جدید**\n\nبیایید یک سرور اضافه کنیم. نام مستعار کوتاه چیست؟ (مثلاً `webserver`)",
        "prompt_hostname": "عالی. نام میزبان یا IP چیست؟",
        "prompt_username": "نام کاربری SSH چیست؟",
        "prompt_auth_method": "چگونه می‌خواهید احراز هویت کنید؟",
        "prompt_password": "لطفاً رمز عبور SSH را وارد کنید.",
        "prompt_key_path": "لطفاً مسیر کامل کلید خصوصی SSH روی سروری که این بات اجرا می‌شود را وارد کنید.",
        "button_auth_key": "🔑 کلید",
        "button_auth_password": "🔒 گذرواژه",
        "server_added": "✅ **سرور `{alias}` با موفقیت اضافه شد!**",
        "connect_menu_prompt": "**یک سرور برای اتصال انتخاب کنید:**",
        "no_servers_configured": "هیچ سروری ثبت نشده است. ابتدا یک سرور اضافه کنید!",
        "server_limit_reached": "⚠️ **حد سرور پر شده است.** طرح شما اجازه {limit} سرور را می‌دهد. یک سرور را حذف یا طرح را ارتقا دهید.",
        "no_servers_to_remove": "🤷 **سروری برای حذف وجود ندارد.**",
        "server_not_found": "❌ **سرور `{alias}` پیدا نشد.**",
        "server_removed": "🗑️ **سرور `{alias}` با موفقیت حذف شد.**",
        "connecting_to_server": "🔌 **در حال اتصال به {alias}...**",
        "connected_to_server": "✅ **به {alias} متصل شد!**\n\nدوست دارید چه کاری انجام دهید؟",
        "error_auth_failed": "❌ **خطای احراز هویت:**\nدسترسی رد شد. نام کاربری، گذرواژه یا کلید SSH را بررسی کنید.",
        "error_connection_refused": "❌ **ارتباط رد شد:**\nدسترسی به `{alias}` ممکن نشد. شاید سرور خاموش است یا پورت 22 بسته است.",
        "error_host_not_found": "❌ **میزبان پیدا نشد:**\nامکان حل آدرس `{alias}` وجود ندارد.\n\n`{error}`",
        "error_code_202012": "❌ **خطای ارتباطی (202012):**\nخطای 202012 هنگام اتصال رخ داد. تنظیمات شبکه یا سرور SSH را بررسی کنید.",
        "error_generic_connection": "❌ **ارتباط ناموفق بود:**\nدر هنگام اتصال به `{alias}` خطای غیرمنتظره‌ای رخ داد.\n\n`{error}`",
        "language_menu_title": "🌐 **تنظیمات زبان**",
        "language_menu_description": "زبان دلخواه خود را انتخاب کنید. زبان فعلی: {language_name}.",
        "language_updated": "✅ زبان به {language_name} تغییر یافت.",
        "language_saved_toast": "زبان ذخیره شد!",
        "language_unsupported": "این زبان پشتیبانی نمی‌شود.",
    },
    "fr": {
        "main_menu_welcome": "🐧 **Bienvenue sur votre bot d’administration Linux !**\n\nQue souhaitez-vous faire ?",
        "button_connect_server": "🔌 Se connecter à un serveur",
        "button_add_server": "➕ Ajouter un serveur",
        "button_remove_server": "➖ Supprimer un serveur",
        "button_language_settings": "🌐 Langue",
        "button_back_main_menu": "🔙 Retour au menu principal",
        "add_server_prompt": "🖥️ **Ajouter un nouveau serveur**\n\nChoisissez un alias court (ex. `webserver`).",
        "prompt_hostname": "Génial. Quel est le nom d'hôte ou l'adresse IP ?",
        "prompt_username": "Et le nom d’utilisateur SSH ?",
        "prompt_auth_method": "Comment souhaitez-vous vous authentifier ?",
        "prompt_password": "Veuillez saisir le mot de passe SSH.",
        "prompt_key_path": "Veuillez saisir le chemin complet vers votre clé privée SSH sur le serveur où tourne ce bot.",
        "button_auth_key": "🔑 Clé",
        "button_auth_password": "🔒 Mot de passe",
        "server_added": "✅ **Serveur `{alias}` ajouté avec succès !**",
        "connect_menu_prompt": "**Sélectionnez un serveur à joindre :**",
        "no_servers_configured": "Aucun serveur n’est configuré. Ajoutez-en un d’abord !",
        "server_limit_reached": "⚠️ **Limite atteinte.** Votre offre autorise {limit} serveurs. Supprimez-en un ou passez à une offre supérieure.",
        "no_servers_to_remove": "🤷 **Aucun serveur à supprimer.**",
        "server_not_found": "❌ **Le serveur `{alias}` est introuvable.**",
        "server_removed": "🗑️ **Serveur `{alias}` supprimé avec succès.**",
        "connecting_to_server": "🔌 **Connexion à {alias}...**",
        "connected_to_server": "✅ **Connecté à {alias} !**\n\nQue voulez-vous faire ?",
        "error_auth_failed": "❌ **Échec de l’authentification :**\nAccès refusé. Vérifiez votre nom d’utilisateur, mot de passe ou clé SSH.",
        "error_connection_refused": "❌ **Connexion refusée :**\nImpossible de joindre `{alias}`. Le serveur est peut-être hors ligne ou le port 22 fermé.",
        "error_host_not_found": "❌ **Hôte introuvable :**\nImpossible de résoudre `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Erreur de connexion (202012) :**\nL’erreur SSH 202012 est survenue. Vérifiez l’hôte distant et la configuration réseau.",
        "error_generic_connection": "❌ **Échec de la connexion :**\nUne erreur inattendue est survenue lors de la connexion à `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Préférences linguistiques**",
        "language_menu_description": "Choisissez votre langue préférée. Langue actuelle : {language_name}.",
        "language_updated": "✅ Langue mise à jour vers {language_name}.",
        "language_saved_toast": "Langue enregistrée !",
        "language_unsupported": "Langue non prise en charge.",
    },
    "de": {
        "main_menu_welcome": "🐧 **Willkommen bei deinem Linux-Admin-Bot!**\n\nWas möchtest du tun?",
        "button_connect_server": "🔌 Mit einem Server verbinden",
        "button_add_server": "➕ Server hinzufügen",
        "button_remove_server": "➖ Server entfernen",
        "button_language_settings": "🌐 Sprache",
        "button_back_main_menu": "🔙 Zurück zum Hauptmenü",
        "add_server_prompt": "🖥️ **Neuen Server hinzufügen**\n\nWie soll der kurze Alias heißen? (z. B. `webserver`)",
        "prompt_hostname": "Super. Wie lautet der Hostname oder die IP-Adresse?",
        "prompt_username": "Und der SSH-Benutzername?",
        "prompt_auth_method": "Wie möchtest du dich authentifizieren?",
        "prompt_password": "Bitte gib das SSH-Passwort ein.",
        "prompt_key_path": "Bitte gib den vollständigen Pfad zu deinem privaten SSH-Schlüssel auf dem Server ein, auf dem dieser Bot läuft.",
        "button_auth_key": "🔑 Schlüssel",
        "button_auth_password": "🔒 Passwort",
        "server_added": "✅ **Server `{alias}` wurde erfolgreich hinzugefügt!**",
        "connect_menu_prompt": "**Wähle einen Server für die Verbindung aus:**",
        "no_servers_configured": "Keine Server konfiguriert. Bitte füge zuerst einen Server hinzu!",
        "server_limit_reached": "⚠️ **Serverlimit erreicht.** Dein Tarif erlaubt {limit} Server. Entferne einen oder upgrade.",
        "no_servers_to_remove": "🤷 **Keine Server zum Entfernen.**",
        "server_not_found": "❌ **Server `{alias}` wurde nicht gefunden.**",
        "server_removed": "🗑️ **Server `{alias}` erfolgreich entfernt.**",
        "connecting_to_server": "🔌 **Verbinde mit {alias}...**",
        "connected_to_server": "✅ **Verbunden mit {alias}!**\n\nWas möchtest du als Nächstes tun?",
        "error_auth_failed": "❌ **Authentifizierung fehlgeschlagen:**\nZugriff verweigert. Prüfe Benutzername, Passwort oder SSH-Schlüssel.",
        "error_connection_refused": "❌ **Verbindung abgelehnt:**\n`{alias}` ist nicht erreichbar. Der Server ist eventuell offline oder Port 22 ist geschlossen.",
        "error_host_not_found": "❌ **Host nicht gefunden:**\n`{alias}` konnte nicht aufgelöst werden.\n\n`{error}`",
        "error_code_202012": "❌ **Verbindungsfehler (202012):**\nSSH-Fehler 202012 ist aufgetreten. Bitte Netzwerk und SSH-Server prüfen.",
        "error_generic_connection": "❌ **Verbindung fehlgeschlagen:**\nBeim Verbinden mit `{alias}` ist ein unerwarteter Fehler aufgetreten.\n\n`{error}`",
        "language_menu_title": "🌐 **Spracheinstellungen**",
        "language_menu_description": "Wähle deine bevorzugte Sprache. Aktuelle Auswahl: {language_name}.",
        "language_updated": "✅ Sprache geändert zu {language_name}.",
        "language_saved_toast": "Sprache gespeichert!",
        "language_unsupported": "Diese Sprache wird nicht unterstützt.",
    },
    "es": {
        "main_menu_welcome": "🐧 **¡Bienvenido a tu bot de administración Linux!**\n\n¿Qué deseas hacer?",
        "button_connect_server": "🔌 Conectarse a un servidor",
        "button_add_server": "➕ Agregar servidor",
        "button_remove_server": "➖ Eliminar servidor",
        "button_language_settings": "🌐 Idioma",
        "button_back_main_menu": "🔙 Volver al menú principal",
        "add_server_prompt": "🖥️ **Agregar un nuevo servidor**\n\n¿Cuál será el alias corto? (ej. `webserver`)",
        "prompt_hostname": "Genial. ¿Cuál es el nombre de host o la dirección IP?",
        "prompt_username": "¿Y el nombre de usuario SSH?",
        "prompt_auth_method": "¿Cómo quieres autenticarte?",
        "prompt_password": "Ingresa la contraseña SSH.",
        "prompt_key_path": "Ingresa la ruta completa a tu clave privada SSH en el servidor donde se ejecuta este bot.",
        "button_auth_key": "🔑 Clave",
        "button_auth_password": "🔒 Contraseña",
        "server_added": "✅ **Servidor `{alias}` agregado correctamente!**",
        "connect_menu_prompt": "**Selecciona un servidor para conectarte:**",
        "no_servers_configured": "No hay servidores configurados. ¡Agrega uno primero!",
        "server_limit_reached": "⚠️ **Límite de servidores alcanzado.** Tu plan permite {limit} servidores. Elimina uno o mejora tu plan.",
        "no_servers_to_remove": "🤷 **No hay servidores para eliminar.**",
        "server_not_found": "❌ **No se encontró el servidor `{alias}`.**",
        "server_removed": "🗑️ **Servidor `{alias}` eliminado correctamente.**",
        "connecting_to_server": "🔌 **Conectando con {alias}...**",
        "connected_to_server": "✅ **Conectado a {alias}.**\n\n¿Qué deseas hacer?",
        "error_auth_failed": "❌ **Autenticación fallida:**\nAcceso denegado. Verifica usuario, contraseña o clave SSH.",
        "error_connection_refused": "❌ **Conexión rechazada:**\nNo se pudo contactar `{alias}`. El servidor puede estar apagado o el puerto 22 cerrado.",
        "error_host_not_found": "❌ **Host no encontrado:**\nNo se pudo resolver `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Error de conexión (202012):**\nSe detectó el error 202012. Revisa la red y el servidor remoto.",
        "error_generic_connection": "❌ **Conexión fallida:**\nOcurrió un error inesperado al conectar con `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Preferencias de idioma**",
        "language_menu_description": "Selecciona tu idioma preferido. Idioma actual: {language_name}.",
        "language_updated": "✅ Idioma cambiado a {language_name}.",
        "language_saved_toast": "¡Idioma guardado!",
        "language_unsupported": "Idioma no compatible.",
    },
    "pt": {
        "main_menu_welcome": "🐧 **Bem-vindo ao seu bot administrador Linux!**\n\nO que deseja fazer?",
        "button_connect_server": "🔌 Conectar a um servidor",
        "button_add_server": "➕ Adicionar servidor",
        "button_remove_server": "➖ Remover servidor",
        "button_language_settings": "🌐 Idioma",
        "button_back_main_menu": "🔙 Voltar ao menu principal",
        "add_server_prompt": "🖥️ **Adicionar novo servidor**\n\nQual será o alias curto? (ex.: `webserver`)",
        "prompt_hostname": "Ótimo. Qual é o hostname ou endereço IP?",
        "prompt_username": "E o nome de usuário SSH?",
        "prompt_auth_method": "Como deseja autenticar?",
        "prompt_password": "Digite a senha SSH.",
        "prompt_key_path": "Digite o caminho completo para sua chave privada SSH no servidor onde este bot está em execução.",
        "button_auth_key": "🔑 Chave",
        "button_auth_password": "🔒 Senha",
        "server_added": "✅ **Servidor `{alias}` adicionado com sucesso!**",
        "connect_menu_prompt": "**Selecione um servidor para conectar:**",
        "no_servers_configured": "Nenhum servidor configurado. Adicione um primeiro!",
        "server_limit_reached": "⚠️ **Limite de servidores atingido.** Seu plano permite {limit} servidores. Remova um ou faça upgrade.",
        "no_servers_to_remove": "🤷 **Não há servidores para remover.**",
        "server_not_found": "❌ **Servidor `{alias}` não encontrado.**",
        "server_removed": "🗑️ **Servidor `{alias}` removido com sucesso.**",
        "connecting_to_server": "🔌 **Conectando a {alias}...**",
        "connected_to_server": "✅ **Conectado a {alias}!**\n\nO que deseja fazer?",
        "error_auth_failed": "❌ **Falha na autenticação:**\nAcesso negado. Verifique usuário, senha ou chave SSH.",
        "error_connection_refused": "❌ **Conexão recusada:**\nNão foi possível alcançar `{alias}`. O servidor pode estar inativo ou a porta 22 fechada.",
        "error_host_not_found": "❌ **Host não encontrado:**\nNão foi possível resolver `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Erro de conexão (202012):**\nOcorreu o erro 202012. Verifique o host remoto e a rede.",
        "error_generic_connection": "❌ **Conexão falhou:**\nUm erro inesperado ocorreu ao conectar em `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Preferências de idioma**",
        "language_menu_description": "Selecione seu idioma preferido. Idioma atual: {language_name}.",
        "language_updated": "✅ Idioma alterado para {language_name}.",
        "language_saved_toast": "Idioma salvo!",
        "language_unsupported": "Idioma não suportado.",
    },
    "it": {
        "main_menu_welcome": "🐧 **Benvenuto nel tuo bot di amministrazione Linux!**\n\nCosa desideri fare?",
        "button_connect_server": "🔌 Connetti a un server",
        "button_add_server": "➕ Aggiungi server",
        "button_remove_server": "➖ Rimuovi server",
        "button_language_settings": "🌐 Lingua",
        "button_back_main_menu": "🔙 Torna al menu principale",
        "add_server_prompt": "🖥️ **Aggiungi un nuovo server**\n\nQual è l'alias breve? (es. `webserver`)",
        "prompt_hostname": "Perfetto. Qual è il nome host o l'indirizzo IP?",
        "prompt_username": "E il nome utente SSH?",
        "prompt_auth_method": "Come vuoi autenticarti?",
        "prompt_password": "Inserisci la password SSH.",
        "prompt_key_path": "Inserisci il percorso completo della tua chiave privata SSH sul server che esegue questo bot.",
        "button_auth_key": "🔑 Chiave",
        "button_auth_password": "🔒 Password",
        "server_added": "✅ **Server `{alias}` aggiunto con successo!**",
        "connect_menu_prompt": "**Seleziona un server a cui connetterti:**",
        "no_servers_configured": "Nessun server configurato. Aggiungine uno prima!",
        "server_limit_reached": "⚠️ **Limite di server raggiunto.** Il tuo piano permette {limit} server. Rimuovine uno oppure esegui un upgrade.",
        "no_servers_to_remove": "🤷 **Nessun server da rimuovere.**",
        "server_not_found": "❌ **Il server `{alias}` non è stato trovato.**",
        "server_removed": "🗑️ **Server `{alias}` rimosso con successo.**",
        "connecting_to_server": "🔌 **Connessione a {alias}...**",
        "connected_to_server": "✅ **Connesso a {alias}!**\n\nCosa vuoi fare?",
        "error_auth_failed": "❌ **Autenticazione fallita:**\nAccesso negato. Controlla utente, password o chiave SSH.",
        "error_connection_refused": "❌ **Connessione rifiutata:**\nImpossibile raggiungere `{alias}`. Il server potrebbe essere offline o la porta 22 chiusa.",
        "error_host_not_found": "❌ **Host non trovato:**\nImpossibile risolvere `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Errore di connessione (202012):**\nSi è verificato l'errore 202012. Verifica host remoto e rete.",
        "error_generic_connection": "❌ **Connessione fallita:**\nSi è verificato un errore imprevisto con `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Preferenze lingua**",
        "language_menu_description": "Seleziona la lingua preferita. Lingua attuale: {language_name}.",
        "language_updated": "✅ Lingua impostata su {language_name}.",
        "language_saved_toast": "Lingua salvata!",
        "language_unsupported": "Lingua non supportata.",
    },
    "ru": {
        "main_menu_welcome": "🐧 **Добро пожаловать в ваш Linux-бот администратора!**\n\nЧто вы хотите сделать?",
        "button_connect_server": "🔌 Подключиться к серверу",
        "button_add_server": "➕ Добавить сервер",
        "button_remove_server": "➖ Удалить сервер",
        "button_language_settings": "🌐 Язык",
        "button_back_main_menu": "🔙 Назад в главное меню",
        "add_server_prompt": "🖥️ **Добавление нового сервера**\n\nКакой короткий псевдоним использовать? (например, `webserver`)",
        "prompt_hostname": "Отлично. Каков адрес хоста или IP?",
        "prompt_username": "И имя пользователя SSH?",
        "prompt_auth_method": "Как вы хотите пройти аутентификацию?",
        "prompt_password": "Введите пароль SSH.",
        "prompt_key_path": "Укажите полный путь к вашему приватному SSH-ключу на сервере, где запущен бот.",
        "button_auth_key": "🔑 Ключ",
        "button_auth_password": "🔒 Пароль",
        "server_added": "✅ **Сервер `{alias}` успешно добавлен!**",
        "connect_menu_prompt": "**Выберите сервер для подключения:**",
        "no_servers_configured": "Серверы не настроены. Сначала добавьте один!",
        "server_limit_reached": "⚠️ **Достигнут предел серверов.** В вашем тарифе доступно {limit} серверов. Удалите один или обновите тариф.",
        "no_servers_to_remove": "🤷 **Нет серверов для удаления.**",
        "server_not_found": "❌ **Сервер `{alias}` не найден.**",
        "server_removed": "🗑️ **Сервер `{alias}` успешно удалён.**",
        "connecting_to_server": "🔌 **Подключение к {alias}...**",
        "connected_to_server": "✅ **Подключено к {alias}!**\n\nЧто хотите сделать?",
        "error_auth_failed": "❌ **Ошибка аутентификации:**\nДоступ запрещён. Проверьте имя пользователя, пароль или ключ SSH.",
        "error_connection_refused": "❌ **Подключение отклонено:**\nНе удалось связаться с `{alias}`. Сервер может быть отключен или порт 22 закрыт.",
        "error_host_not_found": "❌ **Хост не найден:**\nНе удалось разрешить `{alias}`.\n\n`{error}`",
        "error_code_202012": "❌ **Ошибка подключения (202012):**\nОбнаружена ошибка 202012. Проверьте сеть и удалённый сервер.",
        "error_generic_connection": "❌ **Не удалось подключиться:**\nПроизошла непредвиденная ошибка при подключении к `{alias}`.\n\n`{error}`",
        "language_menu_title": "🌐 **Настройки языка**",
        "language_menu_description": "Выберите предпочитаемый язык. Текущий язык: {language_name}.",
        "language_updated": "✅ Язык изменён на {language_name}.",
        "language_saved_toast": "Язык сохранён!",
        "language_unsupported": "Язык не поддерживается.",
    },
    "tr": {
        "main_menu_welcome": "🐧 **Linux yönetim botuna hoş geldin!**\n\nNe yapmak istersin?",
        "button_connect_server": "🔌 Bir sunucuya bağlan",
        "button_add_server": "➕ Sunucu ekle",
        "button_remove_server": "➖ Sunucu sil",
        "button_language_settings": "🌐 Dil",
        "button_back_main_menu": "🔙 Ana menüye dön",
        "add_server_prompt": "🖥️ **Yeni sunucu ekle**\n\nKısa takma ad ne olsun? (örn. `webserver`)",
        "prompt_hostname": "Harika. Ana makine adı veya IP adresi nedir?",
        "prompt_username": "SSH kullanıcı adı nedir?",
        "prompt_auth_method": "Nasıl kimlik doğrulamak istersiniz?",
        "prompt_password": "Lütfen SSH parolasını girin.",
        "prompt_key_path": "Lütfen bu botun çalıştığı sunucudaki SSH özel anahtarınızın tam yolunu girin.",
        "button_auth_key": "🔑 Anahtar",
        "button_auth_password": "🔒 Parola",
        "server_added": "✅ **`{alias}` sunucusu başarıyla eklendi!**",
        "connect_menu_prompt": "**Bağlanmak için bir sunucu seç:**",
        "no_servers_configured": "Yapılandırılmış sunucu yok. Önce bir tane ekle!",
        "server_limit_reached": "⚠️ **Sunucu sınırına ulaşıldı.** Planın {limit} sunucuya izin veriyor. Birini sil veya paketi yükselt.",
        "no_servers_to_remove": "🤷 **Silinecek sunucu yok.**",
        "server_not_found": "❌ **`{alias}` adlı sunucu bulunamadı.**",
        "server_removed": "🗑️ **`{alias}` sunucusu başarıyla silindi.**",
        "connecting_to_server": "🔌 **{alias} bağlantısı kuruluyor...**",
        "connected_to_server": "✅ **{alias} sunucusuna bağlandın!**\n\nNe yapmak istersin?",
        "error_auth_failed": "❌ **Kimlik doğrulama başarısız:**\nErişim reddedildi. Kullanıcı adı, parola veya SSH anahtarını kontrol et.",
        "error_connection_refused": "❌ **Bağlantı reddedildi:**\n`{alias}` erişilemedi. Sunucu kapalı olabilir ya da 22 numaralı port kapalıdır.",
        "error_host_not_found": "❌ **Sunucu bulunamadı:**\n`{alias}` çözümlenemedi.\n\n`{error}`",
        "error_code_202012": "❌ **Bağlantı hatası (202012):**\n202012 hatası oluştu. Ağ ve uzak sunucuyu kontrol et.",
        "error_generic_connection": "❌ **Bağlantı başarısız:**\n`{alias}` sunucusuna bağlanırken beklenmeyen bir hata oluştu.\n\n`{error}`",
        "language_menu_title": "🌐 **Dil tercihleri**",
        "language_menu_description": "Tercih ettiğin dili seç. Mevcut dil: {language_name}.",
        "language_updated": "✅ Dil {language_name} olarak güncellendi.",
        "language_saved_toast": "Dil kaydedildi!",
        "language_unsupported": "Bu dil desteklenmiyor.",
    },
    "zh": {
        "main_menu_welcome": "🐧 **欢迎使用 Linux 管理机器人！**\n\n需要做什么？",
        "button_connect_server": "🔌 连接服务器",
        "button_add_server": "➕ 添加服务器",
        "button_remove_server": "➖ 删除服务器",
        "button_language_settings": "🌐 语言",
        "button_back_main_menu": "🔙 返回主菜单",
        "add_server_prompt": "🖥️ **添加新服务器**\n\n请提供一个简短的别名（如 `webserver`）。",
        "prompt_hostname": "很好。主机名或 IP 地址是什么？",
        "prompt_username": "SSH 用户名是什么？",
        "prompt_auth_method": "您想如何进行认证？",
        "prompt_password": "请输入 SSH 密码。",
        "prompt_key_path": "请输入该机器人运行服务器上 SSH 私钥的完整路径。",
        "button_auth_key": "🔑 密钥",
        "button_auth_password": "🔒 密码",
        "server_added": "✅ **服务器 `{alias}` 添加成功！**",
        "connect_menu_prompt": "**请选择要连接的服务器：**",
        "no_servers_configured": "尚未配置服务器，请先添加！",
        "server_limit_reached": "⚠️ **已达到服务器上限。** 当前套餐最多支持 {limit} 台服务器。请删除一个或升级套餐。",
        "no_servers_to_remove": "🤷 **没有可删除的服务器。**",
        "server_not_found": "❌ **未找到服务器 `{alias}`。**",
        "server_removed": "🗑️ **服务器 `{alias}` 已成功删除。**",
        "connecting_to_server": "🔌 **正在连接 {alias}...**",
        "connected_to_server": "✅ **已连接到 {alias}!**\n\n下一步要做什么？",
        "error_auth_failed": "❌ **身份验证失败：**\n拒绝访问。请检查用户名、密码或 SSH 密钥。",
        "error_connection_refused": "❌ **连接被拒绝：**\n无法访问 `{alias}`。服务器可能宕机或 22 端口关闭。",
        "error_host_not_found": "❌ **找不到主机：**\n无法解析 `{alias}`。\n\n`{error}`",
        "error_code_202012": "❌ **连接错误 (202012)：**\n出现 202012 错误。请检查网络和远程主机。",
        "error_generic_connection": "❌ **连接失败：**\n连接 `{alias}` 时发生意外错误。\n\n`{error}`",
        "language_menu_title": "🌐 **语言设置**",
        "language_menu_description": "请选择偏好语言。当前语言：{language_name}。",
        "language_updated": "✅ 语言已切换为 {language_name}。",
        "language_saved_toast": "语言已保存！",
        "language_unsupported": "不支持该语言。",
    },
    "ja": {
        "main_menu_welcome": "🐧 **Linux 管理ボットへようこそ！**\n\n次に何をしますか？",
        "button_connect_server": "🔌 サーバーに接続",
        "button_add_server": "➕ サーバーを追加",
        "button_remove_server": "➖ サーバーを削除",
        "button_language_settings": "🌐 言語",
        "button_back_main_menu": "🔙 メインメニューへ戻る",
        "add_server_prompt": "🖥️ **新しいサーバーを追加**\n\n短いエイリアスは何にしますか？（例: `webserver`）",
        "prompt_hostname": "いいですね。ホスト名またはIPアドレスは何ですか？",
        "prompt_username": "SSH ユーザー名は？",
        "prompt_auth_method": "どのように認証しますか？",
        "prompt_password": "SSH パスワードを入力してください。",
        "prompt_key_path": "このボットを実行しているサーバー上の SSH 秘密鍵のフルパスを入力してください。",
        "button_auth_key": "🔑 鍵",
        "button_auth_password": "🔒 パスワード",
        "server_added": "✅ **サーバー `{alias}` を追加しました！**",
        "connect_menu_prompt": "**接続するサーバーを選択してください：**",
        "no_servers_configured": "サーバーが設定されていません。まず追加してください。",
        "server_limit_reached": "⚠️ **サーバー数の上限に達しました。** 現在のプランでは最大 {limit} 台までです。削除するかプランをアップグレードしてください。",
        "no_servers_to_remove": "🤷 **削除できるサーバーがありません。**",
        "server_not_found": "❌ **サーバー `{alias}` が見つかりません。**",
        "server_removed": "🗑️ **サーバー `{alias}` を削除しました。**",
        "connecting_to_server": "🔌 **{alias} に接続中...**",
        "connected_to_server": "✅ **{alias} に接続しました！**\n\n何をしますか？",
        "error_auth_failed": "❌ **認証に失敗しました：**\nアクセスが拒否されました。ユーザー名・パスワード・SSH鍵を確認してください。",
        "error_connection_refused": "❌ **接続が拒否されました：**\n`{alias}` に到達できません。サーバーが停止しているか、ポート22が閉じています。",
        "error_host_not_found": "❌ **ホストが見つかりません：**\n`{alias}` を解決できませんでした。\n\n`{error}`",
        "error_code_202012": "❌ **接続エラー (202012)：**\nエラー202012が発生しました。ネットワークとリモートホストを確認してください。",
        "error_generic_connection": "❌ **接続に失敗しました：**\n`{alias}` への接続中に予期せぬエラーが発生しました。\n\n`{error}`",
        "language_menu_title": "🌐 **言語設定**",
        "language_menu_description": "希望する言語を選択してください。現在の言語：{language_name}。",
        "language_updated": "✅ 言語を {language_name} に変更しました。",
        "language_saved_toast": "言語を保存しました！",
        "language_unsupported": "この言語はサポートされていません。",
    },
    "ko": {
        "main_menu_welcome": "🐧 **Linux 관리 봇에 오신 것을 환영합니다!**\n\n무엇을 도와드릴까요?",
        "button_connect_server": "🔌 서버 연결",
        "button_add_server": "➕ 서버 추가",
        "button_remove_server": "➖ 서버 삭제",
        "button_language_settings": "🌐 언어",
        "button_back_main_menu": "🔙 메인 메뉴로",
        "add_server_prompt": "🖥️ **새 서버 추가**\n\n짧은 별칭은 무엇으로 할까요? (예: `webserver`)",
        "prompt_hostname": "좋아요. 호스트 이름 또는 IP 주소는 무엇인가요?",
        "prompt_username": "SSH 사용자 이름은 무엇인가요?",
        "prompt_auth_method": "어떻게 인증하시겠어요?",
        "prompt_password": "SSH 비밀번호를 입력하세요.",
        "prompt_key_path": "이 봇이 실행 중인 서버에 있는 SSH 개인 키의 전체 경로를 입력하세요.",
        "button_auth_key": "🔑 키",
        "button_auth_password": "🔒 비밀번호",
        "server_added": "✅ **서버 `{alias}`가 성공적으로 추가되었습니다!**",
        "connect_menu_prompt": "**연결할 서버를 선택하세요:**",
        "no_servers_configured": "설정된 서버가 없습니다. 먼저 추가하세요!",
        "server_limit_reached": "⚠️ **서버 한도에 도달했습니다.** 현재 요금제는 최대 {limit}대까지 허용합니다. 서버를 삭제하거나 업그레이드하세요.",
        "no_servers_to_remove": "🤷 **삭제할 서버가 없습니다.**",
        "server_not_found": "❌ **`{alias}` 서버를 찾을 수 없습니다.**",
        "server_removed": "🗑️ **`{alias}` 서버가 성공적으로 삭제되었습니다.**",
        "connecting_to_server": "🔌 **{alias}에 연결 중...**",
        "connected_to_server": "✅ **{alias}에 연결되었습니다!**\n\n무엇을 하시겠습니까?",
        "error_auth_failed": "❌ **인증 실패:**\n접근이 거부되었습니다. 사용자 이름, 비밀번호 또는 SSH 키를 확인하세요.",
        "error_connection_refused": "❌ **연결 거부:**\n`{alias}`에 연결할 수 없습니다. 서버가 꺼져 있거나 22번 포트가 닫혀 있을 수 있습니다.",
        "error_host_not_found": "❌ **호스트를 찾을 수 없음:**\n`{alias}`를 확인할 수 없습니다.\n\n`{error}`",
        "error_code_202012": "❌ **연결 오류 (202012):**\n202012 오류가 발생했습니다. 네트워크와 원격 호스트를 확인하세요.",
        "error_generic_connection": "❌ **연결 실패:**\n`{alias}`에 연결하는 동안 예기치 못한 오류가 발생했습니다.\n\n`{error}`",
        "language_menu_title": "🌐 **언어 설정**",
        "language_menu_description": "선호하는 언어를 선택하세요. 현재 언어: {language_name}.",
        "language_updated": "✅ 언어가 {language_name}(으)로 변경되었습니다.",
        "language_saved_toast": "언어가 저장되었습니다!",
        "language_unsupported": "지원되지 않는 언어입니다.",
    },
    "hi": {
        "main_menu_welcome": "🐧 **आपके Linux एडमिन बॉट में स्वागत है!**\n\nआप क्या करना चाहेंगे?",
        "button_connect_server": "🔌 सर्वर से कनेक्ट करें",
        "button_add_server": "➕ सर्वर जोड़ें",
        "button_remove_server": "➖ सर्वर हटाएँ",
        "button_language_settings": "🌐 भाषा",
        "button_back_main_menu": "🔙 मुख्य मेनू पर वापस जाएँ",
        "add_server_prompt": "🖥️ **नया सर्वर जोड़ें**\n\nकृपया एक छोटा उपनाम बताएं (जैसे `webserver`).",
        "prompt_hostname": "बहुत बढ़िया। होस्टनेम या IP पता क्या है?",
        "prompt_username": "SSH उपयोगकर्ता नाम क्या है?",
        "prompt_auth_method": "आप कैसे प्रमाणीकरण करना चाहेंगे?",
        "prompt_password": "कृपया SSH पासवर्ड दर्ज करें।",
        "prompt_key_path": "कृपया उस सर्वर पर SSH निजी कुंजी का पूरा पथ दर्ज करें जहाँ यह बॉट चल रहा है।",
        "button_auth_key": "🔑 कुंजी",
        "button_auth_password": "🔒 पासवर्ड",
        "server_added": "✅ **सर्वर `{alias}` सफलतापूर्वक जोड़ दिया गया!**",
        "connect_menu_prompt": "**कनेक्ट करने के लिए सर्वर चुनें:**",
        "no_servers_configured": "कोई सर्वर कॉन्फ़िगर नहीं है। पहले एक जोड़ें!",
        "server_limit_reached": "⚠️ **सर्वर सीमा पूरी हो गई।** आपके प्लान में अधिकतम {limit} सर्वर शामिल हैं। कोई सर्वर हटाएँ या प्लान अपग्रेड करें.",
        "no_servers_to_remove": "🤷 **हटाने के लिए कोई सर्वर नहीं है।**",
        "server_not_found": "❌ **सर्वर `{alias}` नहीं मिला।**",
        "server_removed": "🗑️ **सर्वर `{alias}` सफलतापूर्वक हटाया गया।**",
        "connecting_to_server": "🔌 **{alias} से कनेक्ट किया जा रहा है...**",
        "connected_to_server": "✅ **{alias} से कनेक्ट हो गया!**\n\nअब क्या करना चाहेंगे?",
        "error_auth_failed": "❌ **प्रमाणीकरण विफल:**\nपहुंच अस्वीकार। उपयोगकर्ता नाम, पासवर्ड या SSH कुंजी जांचें।",
        "error_connection_refused": "❌ **कनेक्शन अस्वीकृत:**\n`{alias}` से संपर्क नहीं हो सका। सर्वर बंद हो सकता है या पोर्ट 22 ब्लॉक है।",
        "error_host_not_found": "❌ **होस्ट नहीं मिला:**\n`{alias}` को हल नहीं किया जा सका।\n\n`{error}`",
        "error_code_202012": "❌ **कनेक्शन त्रुटि (202012):**\nत्रुटि 202012 मिली। नेटवर्क और रिमोट सर्वर की जाँच करें।",
        "error_generic_connection": "❌ **कनेक्शन विफल:**\n`{alias}` से कनेक्ट करते समय अप्रत्याशित त्रुटि हुई।\n\n`{error}`",
        "language_menu_title": "🌐 **भाषा प्राथमिकताएँ**",
        "language_menu_description": "अपनी पसंदीदा भाषा चुनें। वर्तमान भाषा: {language_name}।",
        "language_updated": "✅ भाषा {language_name} पर सेट की गई।",
        "language_saved_toast": "भाषा सहेजी गई!",
        "language_unsupported": "यह भाषा समर्थित नहीं है।",
    },
    "ur": {
        "main_menu_welcome": "🐧 **اپنے لینکس ایڈمن بوٹ میں خوش آمدید!**\n\nآپ کیا کرنا چاہتے ہیں؟",
        "button_connect_server": "🔌 سرور سے جڑیں",
        "button_add_server": "➕ سرور شامل کریں",
        "button_remove_server": "➖ سرور حذف کریں",
        "button_language_settings": "🌐 زبان",
        "button_back_main_menu": "🔙 مرکزی مینو پر واپس جائیں",
        "add_server_prompt": "🖥️ **نیا سرور شامل کریں**\n\nبراہ کرم ایک مختصر نام بتائیں (مثلاً `webserver`).",
        "prompt_hostname": "بہت اچھا۔ میزبان کا نام یا IP ایڈریس کیا ہے؟",
        "prompt_username": "اور SSH صارف نام؟",
        "prompt_auth_method": "آپ تصدیق کس طرح کرنا چاہتے ہیں؟",
        "prompt_password": "براہ کرم SSH پاس ورڈ درج کریں۔",
        "prompt_key_path": "براہ کرم اس سرور پر اپنے SSH نجی کلید کا مکمل راستہ درج کریں جہاں یہ بوٹ چل رہا ہے۔",
        "button_auth_key": "🔑 کلید",
        "button_auth_password": "🔒 پاس ورڈ",
        "server_added": "✅ **سرور `{alias}` کامیابی سے شامل ہو گیا!**",
        "connect_menu_prompt": "**جڑنے کے لیے سرور منتخب کریں:**",
        "no_servers_configured": "کوئی سرور ترتیب نہیں دیا گیا۔ پہلے ایک شامل کریں!",
        "server_limit_reached": "⚠️ **سرور کی حد پوری ہو گئی ہے۔** آپ کے پلان میں زیادہ سے زیادہ {limit} سرور شامل ہیں۔ ایک سرور حذف کریں یا پلان اپ گریڈ کریں.",
        "no_servers_to_remove": "🤷 **حذف کرنے کے لیے کوئی سرور نہیں۔**",
        "server_not_found": "❌ **سرور `{alias}` نہیں ملا۔**",
        "server_removed": "🗑️ **سرور `{alias}` کامیابی سے حذف کر دیا گیا۔**",
        "connecting_to_server": "🔌 **{alias} سے رابطہ کیا جا رہا ہے...**",
        "connected_to_server": "✅ **{alias} سے جڑ گئے!**\n\nاب کیا کریں گے؟",
        "error_auth_failed": "❌ **توثیق ناکام:**\nرسائی مسترد ہوگئی۔ صارف نام، پاس ورڈ یا SSH کلید چیک کریں۔",
        "error_connection_refused": "❌ **کنکشن مسترد:**\n`{alias}` سے رابطہ نہیں ہو سکا۔ ہوسکتا ہے سرور بند ہو یا پورٹ 22 بند ہو۔",
        "error_host_not_found": "❌ **ہوسٹ نہیں ملا:**\n`{alias}` کو حل نہیں کیا جا سکا۔\n\n`{error}`",
        "error_code_202012": "❌ **کنکشن ایرر (202012):**\nغلطی 202012 پیش آئی۔ نیٹ ورک اور ریموٹ سرور کی جانچ کریں۔",
        "error_generic_connection": "❌ **کنکشن ناکام:**\n`{alias}` سے جڑتے وقت غیر متوقع غلطی پیش آئی۔\n\n`{error}`",
        "language_menu_title": "🌐 **زبان کی ترجیحات**",
        "language_menu_description": "اپنی پسند کی زبان منتخب کریں۔ موجودہ زبان: {language_name}۔",
        "language_updated": "✅ زبان {language_name} پر تبدیل کر دی گئی ہے۔",
        "language_saved_toast": "زبان محفوظ ہو گئی!",
        "language_unsupported": "یہ زبان معاونت یافتہ نہیں۔",
    },
}

SUPPORTED_LANGUAGES = tuple(TRANSLATIONS.keys())


def translate(key: str, language: str | None = None, **kwargs: str) -> str:
    """Returns a translated string for the given key."""
    lang = language if language in TRANSLATIONS else DEFAULT_LANGUAGE
    template = TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANGUAGE]).get(key)
    if template is None:
        template = TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key)
    return template.format(**kwargs)


def get_language_label(language: str) -> str:
    """Returns a user-facing label for a language code."""
    return LANGUAGE_LABELS.get(language, language)
